### ISSUE TITLE
Protocols fail to consolidate using ExCoveralls

### ISSUE THREAD

**Issue by netsudo** [parroty/excoveralls#314]
Encountering a strange issue, I've implemented some custom protocols recently and tests were passing fine locally using `mix test`. 

The test that's failing inexplicably essentially grabs the metadata types my protocol is implemented for:
`{_, impl_for} = MyProtocol.__protocol__(:impls)`. 

This returns a list of metadata types just fine, but when I run `mix test --cover`, suddenly the test fails and I get:
`** (MatchError) no match of right hand side value: :not_consolidated`

I've tried consolidating the protocol manually in my test and I get `{:error, :no_beam_info}`

I'm encountering this discrepancy both locally and in our GH actions. Nothing seems to be of interest in our fairly minimal coveralls config, and our test config is setup to consolidate protocols as well. 

Has anybody encountered this? I don't see any issues related to it and I've looked at everything on Google for protocol consolidation in regards to tests and excoveralls.

**Comment by jpbecotte** [comment]
Should be fixed once https://github.com/phoenixframework/phoenix/issues/5831 is delivered.

**Comment by netsudo** [comment]
> Should be fixed once [phoenixframework/phoenix#5831](https://github.com/phoenixframework/phoenix/issues/5831) is delivered.

Thanks for the follow up here. Upgraded to Elixir v1.18 recently and still have issues w/ protocol consolidation with partitioned tests. It seems to be solved for a simple `mix test --cover`

Just curious if you've tried out 1.18 yourself and whether it solved the issue in all cases for you
